/*
 * Smart house service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CreateHouseRequestDevicesIds;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * CreateHouseRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-29T16:35:08.076360+03:00[Europe/Moscow]")

public class CreateHouseRequest {
  @SerializedName("userId")
  private BigDecimal userId = null;

  @SerializedName("houseName")
  private String houseName = null;

  @SerializedName("devicesIds")
  private List<CreateHouseRequestDevicesIds> devicesIds = null;

  public CreateHouseRequest userId(BigDecimal userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(description = "")
  public BigDecimal getUserId() {
    return userId;
  }

  public void setUserId(BigDecimal userId) {
    this.userId = userId;
  }

  public CreateHouseRequest houseName(String houseName) {
    this.houseName = houseName;
    return this;
  }

   /**
   * Get houseName
   * @return houseName
  **/
  @Schema(description = "")
  public String getHouseName() {
    return houseName;
  }

  public void setHouseName(String houseName) {
    this.houseName = houseName;
  }

  public CreateHouseRequest devicesIds(List<CreateHouseRequestDevicesIds> devicesIds) {
    this.devicesIds = devicesIds;
    return this;
  }

  public CreateHouseRequest addDevicesIdsItem(CreateHouseRequestDevicesIds devicesIdsItem) {
    if (this.devicesIds == null) {
      this.devicesIds = new ArrayList<CreateHouseRequestDevicesIds>();
    }
    this.devicesIds.add(devicesIdsItem);
    return this;
  }

   /**
   * Get devicesIds
   * @return devicesIds
  **/
  @Schema(description = "")
  public List<CreateHouseRequestDevicesIds> getDevicesIds() {
    return devicesIds;
  }

  public void setDevicesIds(List<CreateHouseRequestDevicesIds> devicesIds) {
    this.devicesIds = devicesIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateHouseRequest createHouseRequest = (CreateHouseRequest) o;
    return Objects.equals(this.userId, createHouseRequest.userId) &&
        Objects.equals(this.houseName, createHouseRequest.houseName) &&
        Objects.equals(this.devicesIds, createHouseRequest.devicesIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, houseName, devicesIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateHouseRequest {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    houseName: ").append(toIndentedString(houseName)).append("\n");
    sb.append("    devicesIds: ").append(toIndentedString(devicesIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
